using Abp.Domain.Entities.Auditing;
using IBS.VoucherWarehouse.Abstractions;
using System.ComponentModel.DataAnnotations;

namespace IBS.VoucherWarehouse.Modules.VoucherWarehouse.Models;


public class TaxVouchersTypes : BaseEntity<int>
{
    [StringLength(5)]
    public string Code { get; set; }
    [StringLength(100)]
    public string Description { get; set; }
    public bool RequireIdentification { get; set; }
    public string CodeAndDescription { get { return string.Join(" - ", new string[] { Code, Description }); } }
    public string FiscalPrinterCode { get; set; }
    public bool ActiveForSales { get; set; }
    public bool ActiveForPurchases { get; set; }
    public int TaxVoucherLenght { get; set; }
    public string RegularExpression { get; set; }
    public bool IsTaxExempt { get; set; }
    public string Format { get; set; }
    public bool IsAutogenerated { get; set; }
    public bool IsElectronic { get; set; }

    override public string ToString()
    {
        return nameof(TaxVouchersTypes);
    }
}
