using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IBS.VoucherWarehouse.Migrations
{
    /// <inheritdoc />
    public partial class AlterTablesTaxVouchers01 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ActiveForPurchases",
                table: "TaxVouchersTypes");

            migrationBuilder.DropColumn(
                name: "ActiveForSales",
                table: "TaxVouchersTypes");

            migrationBuilder.DropColumn(
                name: "FiscalPrinterCode",
                table: "TaxVouchersTypes");

            migrationBuilder.DropColumn(
                name: "IsAutogenerated",
                table: "TaxVouchersTypes");

            migrationBuilder.DropColumn(
                name: "IsElectronic",
                table: "TaxVouchersTypes");

            migrationBuilder.DropColumn(
                name: "IsTaxExempt",
                table: "TaxVouchersTypes");

            migrationBuilder.DropColumn(
                name: "RegularExpression",
                table: "TaxVouchersTypes");

            migrationBuilder.DropColumn(
                name: "RequireIdentification",
                table: "TaxVouchersTypes");

            migrationBuilder.DropColumn(
                name: "CompanyToProcessId",
                table: "TaxVouchers");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "ActiveForPurchases",
                table: "TaxVouchersTypes",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "ActiveForSales",
                table: "TaxVouchersTypes",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "FiscalPrinterCode",
                table: "TaxVouchersTypes",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutogenerated",
                table: "TaxVouchersTypes",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsElectronic",
                table: "TaxVouchersTypes",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsTaxExempt",
                table: "TaxVouchersTypes",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "RegularExpression",
                table: "TaxVouchersTypes",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "RequireIdentification",
                table: "TaxVouchersTypes",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<int>(
                name: "CompanyToProcessId",
                table: "TaxVouchers",
                type: "int",
                nullable: false,
                defaultValue: 0);
        }
    }
}
